### ISSUE TITLE
Can you build a minified version, too?

### ISSUE THREAD

**Issue by NewAlexandria** [ruidfigueiredo/easykeyjs#5]
36k is small, but why not save space?  

Or do you prefer to let/force each project's asset pipeline handle that?

Thanks

**Comment by ruidfigueiredo** [comment]
You can get the minified version from http://www.easykeyjs.com
I didn't add it to the repo, I'd imagine people would get it from there, and if they want to change something then they'd come here.

**Comment by NewAlexandria** [comment]
:+1:
